Repository gisce/reemote, pull requests merged in 2023-10, with the labels that each got.

#58 FIX - Fix bugs parsing tariffs
  pyreemote/pyreemote/telemeasure.py
Labels: bug, to be merged

#59 Added endpoints for testing and sending generic commands to modem
  api/api/__init__.py
  api/requirements.txt
  pyreemote/pyreemote/telemeasure.py
Labels: enhancement, to be merged

#61 FIX added support to the new REEMOTE_PATH changes
  pyreemote/pyreemote/telemeasure.py
Labels: bug
